#!/system/bin/sh
path="/data/zerotier-one"
bin_name="zerotier-one"
pid_file=$path/pid
busybox="/data/adb/magisk/busybox"
[ -f "/data/adb/ksu/bin/busybox" ] && busybox="/data/adb/ksu/bin/busybox"
bin_status() {
	if [[ $($busybox pidof ${bin_name}) ]]; then
		return 0
	else
		return 1
	fi
}
display_bin_status() {
	if bin_status ; then
		echo -e "\033[32m● zerotier-one is running \033[0m"
	else
		echo -e "\033[31m● zerotier-one is stopped \033[0m"
	fi
}
start_bin() {
	nohup $bin_name > /dev/null 2> $path/error.log &
	echo -n $! > $path/pid
}
start_service() {
	if bin_status ; then
		echo "${bin_name} has been running"
		return
	fi
	start_bin
	ip rule add from all lookup main pref 1
	if bin_status; then
		echo "start success"
	else
		echo "start fail,more information see /data/zerotier-one/error.log"
	fi

}
stop_service() {
	if bin_status ; then
		echo "stopping ${bin_name} service."
		kill $(cat ${pid_file}) || killall ${bin_name}
		while bin_status; do
			sleep 0.5
		done
		forward -D >> /dev/null 2>&1
		# sleep 2
		ip rule del from all lookup main pref 1
	else
		echo "${bin_name} has been stopped"
	fi
	rm -f ${pid_file} >> /dev/null 2>&1
}
case "$1" in
  start)
    start_service
    display_bin_status
    ;;
  stop)
    stop_service
    display_bin_status
    ;;
  restart)
    stop_service
    start_service
    display_bin_status
    ;;
  status)
    display_bin_status
    ;;
  *)
    echo "$0 $1 usage: $0 {start|stop|restart|status}"
    ;;
esac
