name: build with NDK toolchains

on:
  workflow_dispatch:

env:
  api_version: 28 # min. 21
  ndk: r26d # android-ndk-$ndk-linux.zip

jobs:
  build:
    permissions: write-all
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: 获取仓库内容
        uses: actions/checkout@v4
        with:
            path: ZeroTierOneForMagisk

      - name: Checkout ZeroTierOne
        uses: actions/checkout@v4
        with:
          repository: zerotier/ZeroTierOne
          ref: ${{ vars.ZEROTIER_BRANCH }}
          path: ZeroTierOne

      - name: Checkout libnatpmp
        uses: actions/checkout@v4
        with:
          repository: miniupnp/libnatpmp
          path: libnatpmp

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Prepare NDK Toolchain
        run: |
          wget -qO ndk.zip https://dl.google.com/android/repository/android-ndk-$ndk-linux.zip
          unzip -qq ndk.zip "android-ndk-$ndk/toolchains/*" && rm ndk.zip -f

      - name: Patch ZeroTier for Cross-Compile
        run: |
          pip3 install toml
          pwd
          python3 ZeroTierOneForMagisk/build/patch.py

      - name: Build for AArch64
        run: |
          PATH=`pwd`/android-ndk-$ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          NDK_ROOT=`pwd`/android-ndk-$ndk/toolchains/llvm/prebuilt/linux-x86_64

          CC=aarch64-linux-android$api_version-clang
          CXX=aarch64-linux-android$api_version-clang++

          cd libnatpmp
          make clean
          make --silent CC=$CC natpmpc-shared
          cd ..

          cd ZeroTierOne
          make clean
          make --silent -j $(nproc) ZT_DEBUG=0 ZT_SSO_SUPPORTED=0 CC=$CC CXX=$CXX LDFLAGS="-L../libnatpmp" DEFS="-I../libnatpmp -D__GLIBC__=0"
          cd ..
          cd ZeroTierOneForMagisk
          mkdir -p lib
          cp ../ZeroTierOne/zerotier-one zerotier
          cp $NDK_ROOT/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so lib
    
      - name: Archive project
        run: zip -r project.zip ZeroTierOneForMagisk  # 创建项目的压缩包

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: project-archive
            path: project.zip
    #   - name: Create Tag
    #     uses: mathieudutour/github-tag-action@v5.6
    #     with:
    #         github_token: ${{ secrets.GITHUB_TOKEN }}
    #         custom_tag: 1.0.0
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
            tag_name: v1.0.0
            files: project.zip
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}